-- 017: Create cga_records (Flat Table for full assessment summary) - PostgreSQL Compatible
CREATE TABLE IF NOT EXISTS cga_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    hn VARCHAR(20),
    full_name VARCHAR(150),
    assessed_date DATE,
    
    -- Basic Info
    age INTEGER,
    education VARCHAR(50),
    caregiver_name VARCHAR(150),
    caregiver_relation VARCHAR(100),
    emergency_phone VARCHAR(50),
    
    -- Health & Habits
    smoke VARCHAR(50),
    alcohol VARCHAR(50),
    
    -- Scores & Results
    mmse_score INTEGER DEFAULT 0,
    mmse_result VARCHAR(50), 
    
    tgds_score INTEGER DEFAULT 0,
    tgds_result VARCHAR(50), 
    suicide_risk VARCHAR(50), 
    
    -- Other Assessments
    incontinence VARCHAR(50), 
    sleep_problem VARCHAR(50), 
    
    -- Sensory (Vision/Hearing)
    vision_left VARCHAR(50),
    vision_right VARCHAR(50),
    hearing_left VARCHAR(50),
    hearing_right VARCHAR(50),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: Foreign Keys are optional here depending on if you have sync'd parent tables.
-- If encounters/patients exist on Cloud, you can add FKs. For now, we keep it loose for easy syncing.
CREATE INDEX IF NOT EXISTS idx_cga_records_hn ON cga_records (hn);
CREATE INDEX IF NOT EXISTS idx_cga_records_date ON cga_records (assessed_date);
